# 256 colors and true color / undercurls
set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-command "zsh"
set -g base-index 1				# start indexing windows at 1
set -g mouse on					# enable mouse support
set -g set-clipboard on			# enable OS clipboard capabilities

set -g status-position bottom		# place the status bar at bottom
set -g status-interval 2		# configure status bar update interval
setw -g mode-keys vi
set -g renumber-windows on
set -sg escape-time 10			# reduce escape delay (important for neovim)
set -g focus-events on			# notify neovim on pane focus changes
set -gq extended-keys on		# pass through extended key combos (Ghostty)
set -g history-limit 50000

bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'samharju/tmux-synthweave-theme'

run '~/.tmux/plugins/tpm/tpm'
